
export default {
  login:{
		login:"Sign in",
    reg:"Sign Up",
    tip:"Enter Email to create an account.",
    srsjh:"Please Enter Email",
    srmm:"Please Enter Possword",
    goReg:"Don't have an account?",
    wjmm:"Forgot your password?",
    srzh:"Please Enter account",
    zcsrmm:"Please Enter Possword again",
    sryzm:"Please Enter code",
    Register:"Register",
    goLogin:"Already have an account?",
    code:"Get Code",
    send:"Send Success",
    dlcg:"Login success",
    mmbyz:"passwords are inconsistent",
    zccg:"Register success",
    forgot:"Forgot password",
    tip1:"Enter your phone number",
    ok:"OK",
    xgcg:"Change success"
	},
  home:{
    home:"Home",
    market:"Market",
    contact:"Contact INFO",
    faq:"FAQS",
    login:"Log in",
    tip:"Do you have any questions? Contact us",
    contactus:"Contact us",
    min:"Min.Purchase",
    date:"Listing Date",
    intro:"Introduction",
    buy:"BUY",
    srsl:"Please enter the quantity purchased",
    srzfmm:"Please enter pay password",
    cancel:"Cancel",
    confirm:"Verift",
    szzfmm:"Please set the payment password first",
    success:"Success",
    title:"FAQ – Frequently asked questions",
    addr:"Address",
    write:"Write to us",
    name:"Name",
    firstName:"First name",
    email:'Email',
    phone:"Phone",
    message:"Message",
    warn:"I have read and understood the privacy policy. I agree to the electronic storage ancprocessing of my entered data for the purpose of answering my enquiry.",
    send:"Send",
    srmz:"Please enter your name",
    srx:"Please enter your first name",
    sryx:"Please enter your email",
    srsj:"Please enter your phone",
    srxx:"Please enter your message",
    tyxy:"Please read and agree to the agreement"
  },
  kyc:{
    kyc:"KYC",
    xgmm:"Change password",
    xgzfmm:"Change pay password",
    order:"Historical order",
    about:"About us",
    cz:"Deposit",
    tx:"Withdraw",
    jl:"Record",
    sclb:"Watch list",
    tc:"Log out",
    back:"Back Home",
    rule:"Authentication rule",
    tip1:"1. New users must pass real-name authentication after registration.",
    tip2:"2. The name and ID number will not be changed once verified.",
    tip3:"3. Your real name must match your withdrawal card name.",
    id:"ID",
    zm:"Front",
    fm:"Back",
    srid:"Please enter your ID",
    sczm:"Please upload front",
    scfm:"Please upload back",
    old:"Old",
    new:"New",
    qd:"Confirm",
    srjmm:"Please enter your old password",
    srxmm:"Please enter new password",
    qrmm:"Please enter new password again",
    nc:"Name/Code",
    pq:"Price/Quantity",
    zt:"Status",
    cz:"Operate",
    jxz:"Ongoing",
    ywc:"Finished",
    sell:"Agency"
  },
  recharge:{
    tip1:"Manual Rrcharge",
    funds:"FUNDS AMOUNT",
    transfer:"Transfer range",
    srsl:"Please enter amount",
    czxx:"Deposit Method",
    kh:"Cardholder Name",
    yhmc:"Card Number",
    type:"Card Type",
    scpz:"UPLOAD PROOF",
    qd:"Proceed",
    min:"The quantity cannot be less than:",
    max:"'The quantity cannot exceed:'",
    qscpz:"Please upload the voucher"
  },
  tx:{
    title:"Withdraw",
    tip:"Enter Amount",
    tip1:'1. only available amount can be withdraw you can check "profile" and click on "available amount".',
    tip2:"2. The money used today for order can only be withdrawn after the order is cancelled.",
    tip3:"3. Withdrawal: 09:00am - 17:00pm (Monday - Friday).",
    ye:"Trading balance",
    gz:"withdrawal range",
    info:"Withdraw Info",
    pwd:"Password",
    srkh:"Please Enter card number",
    srdz:"'Please Enter address'",
    srmz:"'Please Enter name'",
    srdh:'Please Enter email',
    zhyebz:"Insufficient account balance",
    ysxy:"Privacy Agreement",
    wyzx:"I already know",
    warn:"Note: All payment progress matters will be notified by email. Please check your email carefully"
  }
}