export default {
  login: {
    login: "登录",
    reg: "注册",
    tip: "请输入邮箱号码以创建账户。",
    srsjh: "请输入邮箱号码",
    srmm: "请输入密码",
    goReg: "还没有账户？",
    wjmm: "忘记密码？",
    srzh: "请输入账户",
    zcsrmm: "请再次输入密码",
    sryzm: "请输入验证码",
    Register: "注册",
    goLogin: "已经有账户？",
    code: "获取验证码",
    send: "发送成功",
    dlcg: "登录成功",
    mmbyz: "密码不一致",
    zccg: "注册成功",
    forgot: "忘记密码",
    tip1: "请输入您的手机号码",
    ok: "确定",
    xgcg: "修改成功"
  },
  home: {
    home: "首页",
    market: "市场",
    contact: "联系信息",
    faq: "常见问题",
    login: "登录",
    tip: "您有任何问题吗？联系我们",
    contactus: "联系我们",
    min: "最低购买",
    date: "上市日期",
    intro: "介绍",
    buy: "购买",
    srsl: "请输入购买数量",
    srzfmm: "请输入支付密码",
    cancel: "取消",
    confirm: "确认",
    szzfmm: "请先设置支付密码",
    success: "成功",
    title: "常见问题 – 常见问题解答",
    addr: "地址",
    write: "给我们写信",
    name: "姓名",
    firstName: "名字",
    email: '电子邮件',
    phone: "电话",
    message: "消息",
    warn: "我已阅读并理解隐私政策。我同意电子存储和处理我输入的数据，以便回答我的咨询。",
    send: "发送",
    srmz: "请输入您的姓名",
    srx: "请输入您的名字",
    sryx: "请输入您的电子邮件",
    srsj: "请输入您的电话",
    srxx: "请输入您的消息",
    tyxy: "请阅读并同意协议"
  },
  kyc: {
    kyc: "KYC",
    xgmm: "更改密码",
    xgzfmm: "更改支付密码",
    order: "历史订单",
    about: "关于我们",
    cz: "存款",
    tx: "付款",
    jl: "记录",
    sclb: "观察列表",
    tc: "登出",
    back: "返回首页",
    rule: "认证规则",
    tip1: "1. 新用户注册后必须通过实名认证。",
    tip2: "2. 一旦验证，姓名和身份证号码将无法更改。",
    tip3: "3. 您的真实姓名必须与提款卡上的姓名匹配。",
    id: "身份证",
    zm: "正面",
    fm: "背面",
    srid: "请输入您的身份证",
    sczm: "请上传正面",
    scfm: "请上传背面",
    old: "旧",
    new: "新",
    qd: "确认",
    srjmm: "请输入您的旧密码",
    srxmm: "请输入新密码",
    qrmm: "请再次输入新密码",
    nc: "姓名/代码",
    pq: "价格/数量",
    zt: "状态",
    cz: "操作",
    jxz: "进行中",
    ywc: "完成",
    sell: "代售"
  },
  recharge: {
    tip1: "手动充值",
    funds: "资金金额",
    transfer: "转账范围",
    srsl: "请输入金额",
    czxx: "存款方式",
    kh: "持卡人姓名",
    yhmc: "卡号",
    type: "卡类型",
    scpz: "上传凭证",
    qd: "继续",
    min: "数量不能少于：",
    max: "数量不能超过：",
    qscpz: "请上传凭证"
  },
  tx: {
    title: "付款",
    tip: "输入金额",
    tip1: '1. 只有可用金额可以提取，您可以查看“股票详情”查看可用余额。',
    tip2: "2. 今日用于订单的资金只能在订单取消后提取。",
    tip3: "3. 提款时间：上午9:00 - 下午5:00（周一至周五美国时间）。",
    ye: "可用余额",
    gz: "提款范围",
    info: "提款信息",
    pwd: "密码",
    srkh: "请输入卡号",
    srdz: "请输入地址",
    srmz: "请输入姓名",
    srdh: "请输入手机",
    zhyebz: "账户余额不足",
    ysxy:"隐私协议",
    wyzx:"我已知晓",
    warn:"备注:所有付款进程事项,会有邮件通知,注意查看邮件"
  }
}
